check labels 22

diff --git a/.github/workflows/check_labels.yml b/.github/workflows/check_labels.yml
--- a/.github/workflows/check_labels.yml
+++ b/.github/workflows/check_labels.yml
@@ -15,11 +15,32 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Listing v2
-        env: 
+        env:
           LIST_LABEL: ${{ toJson(github.event.pull_request.labels.*.name) }}
         run: |
           for i in ${!LIST_LABEL[@]}; do
             echo "element $i is ${LIST_LABEL[$i]}"
+          done
+  list_of_labels_v3:
+    name: Listing labels v3
+    runs-on: ubuntu-latest
+    steps:
+      - name: Listing v3
+        env:
+          LIST_LABEL: ${{ toJson(github.event.pull_request.labels.*.name) }}
+        run: |
+          list_length=$(echo "$LIST_LABEL" | jq length)
+          list_length=$((list_length - 1))
+          for i in `seq 0 $list_length`; do
+            module=$(echo "$LIST_LABEL" | jq .["$i"] | cut -d "\"" -f 2)
+            ls "${module}" 2>/dev/null
+            command_result=$?
+            echo "Result -> $command_result"
+            if [ "$command_result" -gt 0 ]; then
+              echo "FOUND!"
+            else
+              echo "NOT FOUND!"
+            fi
           done
   get_labels:
     name: Getting Labels
